### ISSUE TITLE
Definir projeto para trabalhar com o Git Flow

### ISSUE THREAD

**Issue by IanoMaciel** [IanoMaciel/SUPER-GCS#1]
**Descrição**
A ideia dessa issue é listar a algumas tarefas que serão realizada neste repositótio

**Objetivo **
Definir um projeto simples (ou um artefato) para trabalhar com o gitflow

**Tarefas**
- [ ] Fazer um brainstorming com os possíveis temas;
- [ ] Listar o problema;
- [ ] Pensar em uma solução;

**Checklist**
- [ ] Tema definido
- [ ] Problema encontrado 
- [ ] Solução definida

**Comment by IanoMaciel** [comment]
@natasharhayane, já discutimos sobre o possível tema para o projeto e já definimos um, então irei fechar essa issue. Tudo bem pra você? Deseja acrescentar algo?

**Comment by natasharhayane** [comment]
@IanoMaciel estou de acordo, creio que já podemos fechar o issue e trabalhar na parte de desenvolvimento.
